on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle
      - run: ./gradlew spotlessCheck build --no-daemon
      - uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: reports (${{ matrix.os }})
          path: build/reports
