on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle
      - run: ./gradlew spotlessCheck build
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: build/reports
